Add tag difficulty
Orange-OpenSource/a11y-guidelines pull request #246
Opened 2021-10-22 08:11 UTC by SimonF30

@Aniort @PigeardSylvain 

Pr pour l'ajout des tags
 - modification sur la gestion des titres h1 pour les articles qui possèdes des tags
 - ajout des tags difficultés
 - modification des classes badges qui ne prennent pas le focus
 
A vérifier : 
 - Voir si la vocalisation des tags est bonne ( masquage accessible ? )
 -  Vérifier les différents niveaux de difficultés que j'ai mis sur les articles

2021-11-04 10:36 UTC, SimonF30 commented
@PigeardSylvain  @Aniort 

j'ai essayé d'améliorer la vocalisation, plusieurs choses

Dans la liste des articles :
- J'ai mis les badges juste en dessous des titres
- Renommer "Filtres" en "Filtrer par thématiques"
- Enlever le titre de la navigation sinon le aria-labelledby n'est pas prononcé à la tabulation  https://github.com/Access4all/adg/issues/287
- Rajouter un aria-labelledby sur la liste des tags pour que "Thématiques associés" soit prononcé à la tabulation (en train de me dire si c'est pas mieux de mettre aria-describedby)
- J'ai enlevé tout les masquages accessibles (""filtre" + nom du tag") ça polluaient énormément la vocalisation 


voilà c'est à peu près tout, j’attends vos retours

2021-11-04 13:36 UTC, PigeardSylvain commented
Dans les articles je mettrais bien le texte "thématique associée" en masquage accessible et j'ajouterai la date pour faire un semblant d'en-tête : 
![image](https://user-images.githubusercontent.com/13221271/140322922-d8adbf8a-dd22-42a5-bf3f-ff18e7b4dc47.png)

2021-11-04 14:32 UTC, Aniort requested changes
ok avec les remarques de @PigeardSylvain 
sinon le reste c bien impec !

2021-11-05 10:57 UTC, SimonF30 commented
j'ai fait l'update

2021-11-16 14:25 UTC, SimonF30 commented
@Aniort @PigeardSylvain vous pouvez check?
j'ai un nouvel article à écrire, ça permettra de partir sur les mêmes bases

2021-11-17 14:31 UTC, PigeardSylvain approved these changes

2021-11-18 15:17 UTC, merged