Feature/article table sortable
Orange-OpenSource/a11y-guidelines pull request #292
Opened 2022-03-04 15:15 UTC by SimonF30

2022-03-10 11:27 UTC, Aniort requested changes
bon début...
on attend le reste ;)

2022-04-08 13:42 UTC, SimonF30 commented
@Aniort @PigeardSylvain J'ai mis à jours l'article

Pour le dernier tableau j'ai repris celui de nos déclaration que j'ai modifié avec des id et des header,

Je vous laisse checker tout ça :)

2022-04-08 15:29 UTC, Aniort reviewed
1èrerelecture, regarde car j'ai dées doutes sur ce que tu veux dire losque tu dis "Dans le tableau ci-dessus, il y a deux choses à retenir&nbsp;:"
je s&ais pas s&i j'ai bien compris ces deux points d!

2022-04-12 10:06 UTC, PigeardSylvain approved these changes
Ok pour moi

2022-04-13 10:20 UTC, Aniort commented
qqs modif de fond mais surtout d'orthographe

2022-04-20 12:03 UTC, Aniort approved these changes
ok

2022-04-20 12:07 UTC, merged