Maj outils tests auto
Orange-OpenSource/a11y-guidelines pull request #40
Opened 2020-10-13 14:33 UTC by MarionPus

màj article sur les tests auto (Axe et Wave) version FR et EN + captures d'écran obsolètes

2020-10-13 14:35 UTC, ffoodd commented on src/fr/web/outils/methodes-et-outils-de-test/extensions-navigateur.md
> +* https://ffoodd.github.io/a11y.css/
Miam <3

2020-10-13 14:57 UTC, MarionPus commented
go pour MEP ? 👍

2020-10-13 14:59 UTC, MarionPus commented on src/fr/web/outils/methodes-et-outils-de-test/extensions-navigateur.md
> +* https://ffoodd.github.io/a11y.css/
mince, je suis surveillée !

2020-10-13 15:13 UTC, GaetanBt requested changes
Les images ont des extensions en majuscules `.PNG` mais sont appelées en minuscules : `.png`. Le serveur de Netlify n'a pas l'air d'être sensible à la casse mais on ne peut pas être sûrs que ça soit le cas en prod. C'est possible d'avoir des extensions en minuscule ? :smile: 

Du coup je pense qu'on peut supprimer les deux `aXe.png` qui existaient déjà, elles n'ont pas l'air d'être utilisées ailleurs

2020-10-15 07:51 UTC, ffoodd commented
@GaetanBt Tu voudrais pas brancher [l’image-action de calibre-app](https://github.com/marketplace/actions/image-actions), au passage ? :innocent:

2020-10-15 08:32 UTC, GaetanBt commented
@ffoodd Ah oui tient, je commençais à me dire que j'allais m'en occuper dans un tâche Gulp au même moment que la minification des _assets_. Je n'avais pas cherché du côté des Github Actions. Ça à peut-être même l'air plus approprié !

2020-10-15 11:43 UTC, GaetanBt approved these changes

2020-10-15 12:19 UTC, merged