Maj lien evitement
Orange-OpenSource/a11y-guidelines pull request #427
Opened 2023-05-10 15:31 UTC by damiengomez

Petites modifs sur l'article des liens d'évitement :
- faute d'orthographe
- remplacement des termes "sauter" par "éviter"
- suppression de la partie sur le lien d'évitement fait avec une balise <a> et  un attribut name

2023-06-22 07:54 UTC, SimonF30 requested changes
pourquoi tu as rajouté src/fr/articles/timestamp.md dans le gitignore ?

je pense aussi qu'il faut prendre le réflexe de changer la date de l'article quand on le modifie.

Et enfin, on commence à avoir pas mal de différence entre le site en français et en anglais,
Il faudrait aussi prendre le réflexe de faire les modifs en anglais en même temps qu'en français.

Je vois qu'on a encore l'ancienne version en anglais https://a11y-guidelines.orange.com/en/articles/skip-links-best-practices/,

ce serait pas mal de mettre à jour

2023-06-22 08:36 UTC, damiengomez commented
- Effectivement, la modif avait été faite suite à un point que l'on avait fait avec Vincent.

- l'article sur les timestamp, de mémoire, j'avais commencé à l'écrire et finalement il n'y a rien à en dire, aucune façon particulière de rendre accessible un timestamp, donc je pense que le but était de le viré ? dit moi si je ne m'y suis pas pris de la bonne manière.

- la version du skip link doit effectivement être très vielle, je me le note pour cette été, je le mettrais à jour

2023-06-22 08:56 UTC, SimonF30 commented
Pour le timestamp, il y a aucun fichier sur le repo, donc j'imagine tu dois l'avoir seulement en local, donc supprime le juste en local, le gitignore c'est vraiment pour des fichier particuliers, généralement les builds ou les packages

2023-06-22 08:59 UTC, damiengomez commented
ça roule je vais regarder ça, j'essaye de modifier la date des modifs pour l'article sur les liens d'évitement dans la journée et je relance une push request

2023-08-30 15:07 UTC, damiengomez reviewed
date changé

2024-02-02 09:19 UTC, pya35 approved these changes

2024-02-02 09:20 UTC, merged