Android article
Orange-OpenSource/a11y-guidelines pull request #545
Opened 2024-08-09 13:41 UTC by pya35

2024-08-19 14:54 UTC, MewenLeHo commented on src/fr/articles/how-to-test-android.md
> +En premier lieu, il est nécessaire d'installer certains outils depuis le Play Store Google:
Google :

2024-08-19 14:56 UTC, MewenLeHo commented on src/fr/articles/how-to-test-android.md
> +- « Ouvrir *nom de l’app* »
```suggestion
- « Ouvrir *nom de l'app* »
```

2024-08-19 14:57 UTC, MewenLeHo commented on src/fr/articles/how-to-test-android.md
> +Il est possible d'afficher les libellés et les numéros des éléments interactifs. Aussi, pour qu'une application soit pilotable de la sorte, il faut que les composants interactifs aient un nom accessi
les numéros ?

2024-08-20 09:12 UTC, MewenLeHo commented on src/fr/articles/how-to-test-android.md
> +2. A présent, toutes les fonctionnalités disponibles par gestes tactiles doivent l’être également à l’aide du clavier.
Pas les bonnes apostrophes ;)

2024-08-20 09:15 UTC, MewenLeHo commented on src/en/articles/how-to-test-android.md
> +As the dark mode is used more and more, so it's strongly recommended to test your application by activating “dark mode”.
1. simples quotes only in english so 'dark mode'.
2. As the dark mode is used more and more, it's strongly recommended to test your application by activating 'dark mode' OR As the dark mode is used more and more, it's strongly recommended to test your application by activating 'dark mode'.

2024-08-20 09:16 UTC, MewenLeHo requested changes
Quelques suggestions :)

2024-08-29 13:41 UTC, afrahB requested changes
Replace the title "Testing the accessibility of an iOS application" with "Testing the accessibility of an Android application."

2024-08-29 13:46 UTC, pya35 reviewed
OK

2024-08-29 14:28 UTC, afrahB commented on src/fr/articles/how-to-test-android.md
> +Lorsque « Voice Access » est activé, vous pouvez énoncer des commandes comme :
Ajouter la commande "Afficher les libellés" pour afficher le libellé correspondant à chaque élément cliquable

2024-08-29 14:57 UTC, pya35 reviewed
OK

2024-08-29 14:57 UTC, pya35 commented on src/fr/articles/how-to-test-android.md
> +Lorsque « Voice Access » est activé, vous pouvez énoncer des commandes comme :
déjà fixé par ce commit https://github.com/Orange-OpenSource/a11y-guidelines/pull/545/commits/f446836375c58e3c913c6f5e7d23a6c96696c26c

2024-08-29 15:46 UTC, pya35 commented on src/en/articles/how-to-test-android.md
> +By default, element names are superimposed.  Also, for an application to be controllable in this way, the interactive components must have a simple and consistent accessible name (in particular in th
déjà fixé par ce commit https://github.com/Orange-OpenSource/a11y-guidelines/commit/f446836375c58e3c913c6f5e7d23a6c96696c26c

2024-08-30 09:50 UTC, Aniort approved these changes
relecture ok

2024-10-09 15:36 UTC, pya35 commented
@MewenLeHo @afrahB c'est OK pour vous ?

2024-10-15 13:01 UTC, MewenLeHo approved these changes
LGTM! 🚀

2024-10-15 13:13 UTC, afrahB approved these changes

2024-10-15 13:20 UTC, merged