Update article svg
Orange-OpenSource/a11y-guidelines pull request #595
Opened 2024-12-06 15:22 UTC by pya35

2024-12-17 07:23 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +Important : Quelle que soit la solution retenue, le support navigateurs/aides techniques évoluant très rapidement, pensez à tester vos implémentations sur les configurations les plus utilisées par vo
Pas de majuscule après ":"

2024-12-17 07:24 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
>  <pre><code class="html">
A confirmer avec @Aniort mais on avait dit qu'à partir de maintenant il fallait ajouter à la balise <code> un aria-label un un title pour spécifier le langage du code présenté.

2024-12-17 07:33 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +en second choix, utiliser `aria-label` (mais celà enfrein la première règle d'ARIA, à savoir, ne pas utiliser d'ARIA si une solution native HTML existe)
```suggestion
en second choix, utiliser `aria-label` (mais cela enfreint la première règle d'ARIA, à savoir, ne pas utiliser d'ARIA si une solution native HTML existe)
```

2024-12-17 07:39 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +&nbsp;:
Un peu étrange d'avoir un saut de ligne puis rien de plus que ":" sur une ligne séparée.

2024-12-17 07:45 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +Note : On rajoute `role="img"` pour s'assurer qu'avec macOS Safari, VoiceOver (anciennes versions) annonce bien « image ».
Pas seulement, `role="img"` est indispensable pour que la balise soit considérée comme un élément image, sinon, elle pourrait être ignorée par les TA (cf. Access42).

2024-12-17 07:47 UTC, MewenLeHo requested changes
Quelques commentaires, dont certains à discuter entre relecteurs.
Par contre merci d'ajouter une description afin de garantir que l'on s'y retrouve dans l'historique.

2024-12-18 12:52 UTC, pya35 commented on src/fr/articles/svg-accessibles.md
> +&lt;svg aria-hidden="true"&gt;
@MewenLeHo @Aniort je serais d'avis de le laisser en tant que "note" plutôt que de le mettre en recommandations dans tous les exemples non ? et ça montre qu'on sait évoluer :-)

2024-12-19 10:49 UTC, Aniort commented on src/fr/articles/svg-accessibles.md
>  <pre><code class="html">
oui, on rajoute un aria-label et un title avec le nom du langage utilisé dans le balise code

2024-12-19 10:50 UTC, pya35 commented on src/fr/articles/svg-accessibles.md
>  <pre><code class="html">
ok , aria-label="html" et title=html"

2024-12-19 10:52 UTC, Aniort commented on src/fr/articles/svg-accessibles.md
> +&lt;svg aria-hidden="true"&gt;
je pencherai (car je suis un progressiste qui veut faire avancer les choses ! ) que maintenant, on vire focusable"false" et on le met en Note en disant si vos utilisateurs sont sous IE alors le rajouter

2024-12-19 13:25 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +&lt;svg aria-hidden="true"&gt;
Ok pour moi mais dans ce cas il fait que les supports de formation soient modifiés pour dire la même chose. Donc celui qui fait la modif fait un ticket dans la repo des supports de formation... ;)

2025-01-07 13:29 UTC, pya35 commented on src/fr/articles/svg-accessibles.md
> +&lt;svg aria-hidden="true"&gt;
done https://gitlab.tech.orange/accessibility/trainings/-/issues/13

2025-02-11 15:44 UTC, Aniort reviewed
ok

2025-03-11 08:27 UTC, MewenLeHo requested changes
Some details and it will be ok.

2025-03-11 08:27 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +- https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/
```suggestion
<a href="https://www.deque.com/blog/creating-accessible-svgs/" hreflang="en">XXX</a>
<a href="https://weboverhauls.github.io/demos/svg/" hreflang="en">XXX</a>
<a href="https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html" hreflang="en">XXX</a>
<a href="https://www.slideshare.net/webaxe/svg-icons-and-screen-reader-accessibility" hreflang="en">XXX</a>
<a href="https://github.com/JeremiePat/svg-accessible/blob/master/slides.md" hreflang="en">XXX</a>
<a href="https://www.sarasoueidan.com/blog/accessible-icon-buttons/" hreflang="en">XXX</a>
<a href="https://www.sarasoueidan.com/blog/accessible-icon-buttons/" hreflang="en">XXX</a>
<a href="https://www.smashingmagazine.com/2021/05/accessible-svg-patterns-comparison/" hreflang="en">XXX</a>
```

2025-03-11 08:27 UTC, MewenLeHo commented on src/en/articles/accessible-svg.md
> +updateDate: "2025-02-28"
Do not forget to update this parameter.

2025-03-11 08:27 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +updateDate: "2025-02-28"
Do not forget to update this parameter.

2025-03-11 08:27 UTC, MewenLeHo commented on src/assets/script.js
>              languageWrapper.classList.add('bg-primary', 'd-inline-block', 'p-2', 'mb-0', 'font-weight-bold')
```suggestion
            languageWrapper.classList.add('text-bg-primary', 'd-inline-block', 'p-2', 'mb-0', 'font-weight-bold')
```

2025-03-11 08:27 UTC, MewenLeHo commented on src/assets/script.js
>              languageWrapper.classList.add('bg-primary', 'd-inline-block', 'p-2', 'mb-0', 'font-weight-bold')
You need to update your branche after upgrading to the newest version of Boosted:

> All our helpers and utilities have also been adapted to the new color modes mechanism and automatically switch their colors and background colors depending on the current color mode. As a result, you should for instance now rather use .text-bg-{color} classes instead of .bg-{color} classes when possible for automatic contrast.
(see: https://boosted.orange.com/docs/5.3/migration/)

2025-03-21 09:23 UTC, MewenLeHo requested changes

2025-03-21 09:23 UTC, MewenLeHo commented on src/en/articles/accessible-svg.md
>  In addition, you must make sure that the `svg` tag or one of its children (`<g>`,`<path>`...) does not have any attribute to provide it with an accessible name (` title`, `desc `,` aria- * `…).
```suggestion
In addition, you must make sure that the `svg` tag or one of its children (`<g>`,`<path>`...) does not have any attribute to provide it with an accessible name (`title`, `desc`, `aria- *`, …).
```

2025-03-21 09:23 UTC, MewenLeHo commented on src/en/articles/accessible-svg.md
> +<a href="https://github.com/JeremiePat/svg-accessible/blob/master/slides.md">SVG Accessible ! - Github Jeremie Patonnier</a>
Change the link for the english version; https://github.com/JeremiePat/svg-accessible/blob/master/en/slides.md

2025-03-21 09:23 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +<a href="https://github.com/JeremiePat/svg-accessible/blob/master/slides.md" hreflang="en">SVG Accessible ! - Github Jeremie Patonnier</a>
```suggestion
<a href="https://github.com/JeremiePat/svg-accessible/blob/master/slides.md">SVG Accessible ! - Github Jeremie Patonnier</a>
```

2025-03-21 09:23 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +<a href="https://github.com/JeremiePat/svg-accessible/blob/master/slides.md" hreflang="en">SVG Accessible ! - Github Jeremie Patonnier</a>
You used the link to the french version ;)

2025-03-21 09:23 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +<a href="https://www.deque.com/blog/creating-accessible-svgs/" hreflang="en">Creating Accessible SVGs - Deque</a>
```suggestion
<a href="https://www.deque.com/blog/creating-accessible-svgs/" hreflang="en">Creating Accessible SVGs - Deque (en)</a>
```

2025-03-21 09:23 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +<a href="https://www.deque.com/blog/creating-accessible-svgs/" hreflang="en">Creating Accessible SVGs - Deque</a>
Just a suggestion but it could be good to add `(en)` in the visible name to keep it consistent (see for instance: https://a11y-guidelines.orange.com/fr/articles/veille-octobre-novembre-2024/).
*Just made it on the first line but of course it would be great to add after each link in english.

2025-03-21 09:23 UTC, MewenLeHo commented on src/en/articles/accessible-svg.md
>  ## Ressources (articles that have helped me a lot)
```suggestion
## Webography (articles that have helped me a lot)
```

2025-03-24 11:19 UTC, MewenLeHo requested changes

2025-03-24 11:19 UTC, MewenLeHo commented on src/fr/articles/svg-accessibles.md
> +<a href="https://github.com/JeremiePat/svg-accessible/blob/master/slides.md">SVG Accessible ! - Github Jeremie Patonnier (en)</a>
```suggestion
<a href="https://github.com/JeremiePat/svg-accessible/blob/master/slides.md">SVG Accessible ! - Github Jeremie Patonnier</a>
```

2025-03-24 15:50 UTC, Aniort approved these changes
go to the moon

2025-03-24 15:58 UTC, Aniort approved these changes
reok

2025-03-27 07:41 UTC, MewenLeHo approved these changes

2025-03-28 08:17 UTC, merged