add new must-have checklist
Orange-OpenSource/a11y-guidelines pull request #596
Opened 2024-12-10 08:48 UTC by pya35

2024-12-10 15:55 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"resultat": [["Un attribut lang est présent dans l'élément <code>&lt;html&gt;</code> de la page"], ["La valeur de l'attribut lang correspond à la langue principale du document, exemple : <code><html
Attention ici : les codes HTML dans les exemples sont interprétés : 
![screenshot-deploy-preview-596--a11y-guidelines_netlify_app-2024_12_10-16_55_27](https://github.com/user-attachments/assets/d1b4e0ca-d19f-45fc-b251-8027f63499e5)

2024-12-10 16:00 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"title": "S'assurer que l'information est transmise par un autre moyen que la couleur",
"pas par la couleur" ou "pas **uniquement** par la couleur ?' Il y a une nuance importante car ce n'est pas interdit de transmettre une info par la couleur, ce qui est interdit c'est de ne pas le faire en plus par d'autres biais.

2024-12-10 16:04 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"tests": ["Parcourir la page au clavier à l'aide des touches <kbd>tab</kbd> ou <kbd>shift + tab</kbd>","Utiliser tous les éléments interactifs (en tapant entrer, espace pour les boutons, et les flèc
"les boutons radio" en français ?

2024-12-10 16:07 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"tests": ["Parcourir la page au clavier à l'aide des touches <kbd>tab</kbd> ou <kbd>shift + tab</kbd>","Utiliser tous les éléments interactifs (en tapant entrer, espace pour les boutons, et les flèc
Dommage d'utiliser <kbd>tab</kbd> mais pas <kbd>Enter</kbd> ou <kbd>Space</kbd>, une raison pour cela ?

2024-12-10 16:11 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"resultat": ["L'utilisateur peut mettre pause/relancer les animations, les mouvements, les mises à jour ou les clignotement."],
"les clignotement" => manque un "s" ;)

2024-12-10 16:12 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"verifier": [["Tout ce qui peut être fait à la souris peut être fait au clavier et inversement."],["L'ordre de déplacement du focus conserve une logique de lecture et d'utilisation"],["Le focus ne r
Juste pour pinailler : le premier item de liste termine par un "." mais pas les trois autres.

2024-12-10 16:15 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"tests": ["Utiliser l'inspecteur du navigateur sur l'onglet 'Accessibilité'"],
Guillements double en français (en pensant à les échapper pour ne pas avoir de soucis).
``` suggestion
	"tests": ["Utiliser l'inspecteur du navigateur sur l'onglet \"Accessibilité\""],
```

2024-12-10 16:18 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"exception": "Lorsque le rôle d'un champ de formulaire est évident et non ambigu (champ de recherche accompagné d'un bouton en forme de loupe, case à cocher pour sélectionner une ligne dans un table
C'est un peu jouer à l'avocat du diable mais en si on ne précise pas "**par exemple :** champ de recherche accompagné d'un bouton en forme de loupe, case à cocher pour sélectionner une ligne dans un tableau de données" j'ai peur que certains comprennent que ce seont les seuls cas évidents et non ambigus.

2024-12-10 16:19 UTC, MewenLeHo commented on src/assets/json/checklist/tests-web-checklist-fr.json
> +	"exception": "Lorsque le rôle d'un champ de formulaire est évident et non ambigu (champ de recherche accompagné d'un bouton en forme de loupe, case à cocher pour sélectionner une ligne dans un table
"nom accessible" "ou <span lang="en">accessible name</span>

2024-12-10 16:20 UTC, MewenLeHo requested changes
Quelques commentaires ;)

2024-12-11 08:32 UTC, MewenLeHo approved these changes
LGTM! 🚀

2024-12-16 16:04 UTC, Aniort reviewed
on a pas de version  en anglais ?
et les erreurs, on dit pas quelles doivent etre liées au champ ?

2024-12-16 16:13 UTC, Aniort reviewed
et on parle pas de nom accessible pour le web ?

2024-12-17 16:32 UTC, pya35 commented
> on a pas de version en anglais ? et les erreurs, on dit pas quelles doivent etre liées au champ ?

pas retenu par le groupe de travail, n'est-ce pas un peu trop technique de devoir aller chercher les liens dans le code ?

2024-12-17 16:33 UTC, pya35 commented
> on a pas de version en anglais ? et les erreurs, on dit pas quelles doivent etre liées au champ ?

traduction non terminée, ça sera pour les étrennes de janvier

2024-12-18 15:39 UTC, Aniort approved these changes
go !

2024-12-18 15:59 UTC, merged