[Update] Article Skip links best practices
Orange-OpenSource/a11y-guidelines pull request #601
Opened 2024-12-17 15:11 UTC by MewenLeHo

2024-12-18 12:19 UTC, pya35 commented
> **Note pour les reviewers :**
> 
> Je suis étonné que les versions FR et EN divergent autant : moins de contenus dans la version EN, pas d'exemples de codes, etc. D'où vient cette différence ? Ajouter le contenu manquant fait-il partie du cadre de ce chantier de mise à jour ? (si oui, il faut prévoir du temps supplémentaire pour cette charge).
> 
> @Aniort et @pya35 avez-vous des infos à ce sujet ?

il faut demander à @damiengomez qui est le dernier contributeur sur cet article

2024-12-18 12:49 UTC, damiengomez commented
Déjà discuté avec Mewen, j'avais fait une update pour ajouter des détails et des exemples sur la version française, mais pas pour la version anglaise (pas sûr que j'avais connaissance de l'existence d'une version anglaise à l'époque).

2025-02-10 15:16 UTC, damiengomez commented on src/en/articles/skip-links-best-practices.md
> +2. **section skip links:** positioned before the region that they allow to jump: "Skip the section", "Skip the chapter"
```suggestion
2. **section skip links:** positioned before the region that they allow to skip: "Skip the section", "Skip the chapter"
```

2025-02-10 15:19 UTC, damiengomez commented on src/en/articles/skip-links-best-practices.md
> +We will therefore, thanks to skip links, limit the use of keyboard navigation keys and more generally save actions during intra-page navigation.
```suggestion
We will therefore, thanks to skip links, limit the use of keyboard navigation keys and more generally decrease the gestures to be done when navigating between pages.
```

2025-02-10 15:27 UTC, damiengomez commented on src/en/articles/skip-links-best-practices.md
> +- It is possible to integrate a skip link in the form of an image (such as an 'arrow' with a <code>title</code> attribute) that appears after scrolling down the page. The skip link will allow for a d
```suggestion
- It is possible to embed a skip link as an image (such as an 'arrow' with a <code>title</code> attribute) that appears after scrolling the page. The skip link returns directly to the top of the page. This avoidance link should not hinder the reading or understanding of the information; it should be the last keyboard-focusable element.
```

2025-02-10 17:10 UTC, damiengomez requested changes
Need some corrections in the english version

2025-02-11 13:21 UTC, MewenLeHo commented on src/en/articles/skip-links-best-practices.md
> +- Skip or quick access links should be visually located in the same place on the page and in the same relative order in the source code across all pages of the site.
Not sure about this one, for me 'across' is better here. 🤔

2025-02-11 13:22 UTC, MewenLeHo commented on src/en/articles/skip-links-best-practices.md
> +**Note**: keep in mind that for a skip link to be functional, it should not merely scroll the page to the indicated location (such as the main content). It must allow the user to 'skip' a part of the
```suggestion
**Note**: keep in mind that for a skip link to be functional, it should not simply scroll to the targeted location (such as the main content for instance). It must allow the user to 'skip' a part of the page. If a user activates a 'Go to content' link using the keyboard, on the next <kbd>TAB</kbd>, the focus should move to the main content and not to the next avoidance link. This focus can be achieved by placing an anchor to the next <code>id</code> to target, for example."
```

2025-02-11 13:24 UTC, MewenLeHo commented on src/en/articles/skip-links-best-practices.md
> +**Note**: keep in mind that for a skip link to be functional, it should not merely scroll the page to the indicated location (such as the main content). It must allow the user to 'skip' a part of the
'Simply' is better, thanks.
But I am not ok with 'main location' since it only works it the skip link allows user to go to the main. I changed it for 'targeted location (such as the main content for instance)', is it ok for you @damiengomez?

2025-02-11 15:49 UTC, Aniort approved these changes
ok

2025-02-24 16:05 UTC, damiengomez commented on src/en/articles/skip-links-best-practices.md
> +- Skip or quick access links should be visually located in the same place on the page and in the same relative order in the source code across all pages of the site.
good for me

2025-02-24 16:06 UTC, damiengomez approved these changes

2025-02-26 16:02 UTC, MewenLeHo commented
Will be release on the 3rd of march.

2025-02-28 07:47 UTC, merged