[Update] Article HTML5 & ARIA
Orange-OpenSource/a11y-guidelines pull request #604
Opened 2024-12-20 08:48 UTC by MewenLeHo

Update de l'article HTML5 & ARIA :
FR : https://a11y-guidelines.orange.com/fr/articles/html5-et-aria/
EN: https://a11y-guidelines.orange.com/en/articles/html5-aria/

Liens direct vers les previews :
FR : https://deploy-preview-604--a11y-guidelines.netlify.app/fr/articles/html5-et-aria/
EN: https://deploy-preview-604--a11y-guidelines.netlify.app/en/articles/html5-aria/

2025-01-02 10:38 UTC, MewenLeHo commented on src/fr/articles/html5-et-aria.md
> +Globalement, <abbr>ARIA</abbr> améliore l'accessibilité pour des composants qui ne sont pas nativement présents dans le <abbr>HTML</abbr> (ou pas accessibles notamment certains éléments <abbr>HTML5</
Don't know exactly what to do whit this part of the text.
Techniques listed in https://www.w3.org/WAI/GL/wiki/Category:ARIA_Techniques and https://www.w3.org/WAI/WCAG21/Techniques/ are not the same.
Should we update it based on https://www.w3.org/WAI/WCAG22/Techniques/ ?

2025-02-10 17:08 UTC, damiengomez submitted a review, later dismissed
Need to make some modifications before approve

2025-02-11 15:41 UTC, Aniort requested changes
on est en version 12 d'aria donc maj dans letxt et les liens
sinon ok

2025-02-26 08:09 UTC, damiengomez approved these changes

2025-02-26 15:10 UTC, Aniort approved these changes
woui !

2025-02-26 15:58 UTC, MewenLeHo commented
Will be release on the 15th of march.

2025-03-13 10:06 UTC, damiengomez approved these changes

2025-03-13 10:15 UTC, MewenLeHo commented
For your information @Aniort and @damiengomez, I was checking the article for tomorrow's release and I found a semantic problem.

In the english version, the 'Webography' part was made in markdown:

```
* W3C:
  * [<abbr>ARIA</abbr> specification 1.2](http://www.w3.org/TR/wai-aria/)
  * [<abbr>ARIA</abbr> implementation](http://www.w3.org/TR/wai-aria-practices/)
  * [Use <abbr>ARIA</abbr> with HTML5](http://www.w3.org/TR/aria-in-html/)
  * [<abbr>ARIA</abbr> techniques](https://www.w3.org/WAI/WCAG22/Techniques/)
* [Introduction to <abbr>ARIA</abbr> by Site Point](http://www.sitepoint.com/introduction-wai-aria/)
* [Introduction and link list to <abbr>ARIA</abbr> sources](http://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA)
```

But because it was made with non-breaking spaces instead of normal spaces, it was rendered as:

```
<ul>
  <li>W3C:<br>
    <a href="http://www.w3.org/TR/wai-aria/"><abbr>ARIA</abbr> specification</a><br>
    <a href="http://www.w3.org/TR/wai-aria-practices/"><abbr>ARIA</abbr> implementation</a><br>
    <a href="http://www.w3.org/TR/aria-in-html/">Use <abbr>ARIA</abbr> HTML (5)</a><br>
    <a href="https://www.w3.org/WAI/GL/wiki/Category:ARIA_Techniques"><abbr>ARIA</abbr> techniques in <abbr>WCAG</abbr> 2</a>
  </li>
  <li><a href="http://www.sitepoint.com/introduction-wai-aria/">Introduction to <abbr>ARIA</abbr> by Site Point</a></li>
  <li><a href="http://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA">Introduction and link list to <abbr>ARIA</abbr> sources</a></li>
</ul>
```

so I fixed it to:

```
<ul>
  <li>W3C:
    <ul>
      <li><a href="http://www.w3.org/TR/wai-aria/"><abbr>ARIA</abbr> specification</a></li>
      <li><a href="http://www.w3.org/TR/wai-aria-practices/"><abbr>ARIA</abbr> implementation</a></li>
      <li><a href="http://www.w3.org/TR/aria-in-html/">Use <abbr>ARIA</abbr> HTML (5)</a></li>
      <li><a href="https://www.w3.org/WAI/GL/wiki/Category:ARIA_Techniques"><abbr>ARIA</abbr> techniques in <abbr>WCAG</abbr> 2</a></li>
    </ul>
  </li>
      <li><a href="http://www.sitepoint.com/introduction-wai-aria/">Introduction to <abbr>ARIA</abbr> by Site Point</a></li>
      <li><a href="http://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA">Introduction and link list to <abbr>ARIA</abbr> sources</a></li>
</ul>
```

2025-03-14 09:04 UTC, merged