Develop android en
Orange-OpenSource/a11y-guidelines pull request #86
Opened 2020-11-24 17:18 UTC by Romain-Rs

2020-12-03 17:45 UTC, notabene requested changes

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +- The click zone has a margin around the element of at least 8 dp
This line misses a "." at the end.

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +## Have readable texts
`## Provide readable text`

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +The text can cause readability problems when it is too small or the font has impasto : a minimum text size of 14sp is recommended.
s/impasto/serif/
[NB: impasto is _empâtement_, it's a painting method, while serif is _empattement_, the typography thing 😉 ]

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +Android natively offers the Roboto font which has 16 variants, including many sans serif that are adapted to the readability need : roboto regular, roboto thin, roboto medium, etc... Serif fonts, suc
s/need :/need:/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +- The font is sans-serif
Missing punctuation (this line and line 80 below)

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +This automatic UI update is an issue for accessibility, cause a user could need more time to interact with the elements. This timeout must be adaptable according to the needs of each user.
s/cause/because/
s/could/may/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +An accessibility option named "Time to take action" exists since Android 10, and allows to define its own timeout. By calling this option from the application, it is possible to adapt its interfaces
s/exists since Android 10/was introduced with Android 10/
s/with/according to/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +It is possible to exploit this option through the getRecommendedTimeoutMillis() function. This method supports user-defined timeouts for interactive and non-interactive user interface elements. The r
Backquotes:
```
It is possible to exploit this option through the `getRecommendedTimeoutMillis()` function.
```

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/general-navigation.md
> +- [Construire une vue custom accessible](https://developer.android.com/guide/topics/ui/accessibility/custom-views)
This line and the next would need to either be translated or to state that they're in French and/or point to French-speaking resources.

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/index.md
> +This guide present the different accessibility options of the Android SDK. Through different categories, this guide explains how to use the accessibility attributes and methods, with code examples to
s/present/presents/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/magnification.md
> +The application must implement dynamic text sizes, ensure the good reactivity of the display areas to text magnification (containers that adapt to the size of their content).
s/ensure the good reactivity of the display areas to text magnification/ensure that display areas react properly to text magnification/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/magnification.md
> +- Use a dynamic font size: the "&nbsp;sp&nbsp;". This unit, specific to Android, allows to obtain a font size according to the pixel density of the screen.
`"&nbsp;sp&nbsp;"` → "sp"
Like punctuation mentioned above, quotes in English do not need spaces within.
Please correct several instances within.

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/magnification.md
> +- Manage content overflows: a common mistake is to use a dynamic text size ("sp&nbsp;sp&nbsp;" therefore) without adapting the container. If the text gets bigger, the container must do the same so th
Backquote issue! s/'/`/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +Decorative images, do not require a text alternative and therefore should not be vocalized.
s/,//

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- Images carrying information restore this information through their textual alternatives.
s/restore/convey/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +It is important to provide a text alternative when the information is not available or sufficient natively, as for components providing information by color, shape, position, sound... All components
s/as for/e.g./
s/providing information by/conveying information through/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- Elements are all vocalized and accessible
Punctuation missing (+ line 63)

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +The different types of tabs offered in Android, for example, do not give all the information about their nature and status. It is up to the developer to give this information to the user via the corr
Backquotes missing:
```
("`contentDescription`")
```

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- Any element whose status can be modified during the use of the application must restore its state through its text alternative. For example, an item that can be selected/unselected.
s/restore/convey/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +The example shows tabs above and below a `ViewPager' in one case in `TabLayout' and in the other in `BottomNavigationView'. Tabs are no longer practiced as `TabHost'.
s/'/`/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +The focus order of the default screen reader depends on several parameters: the "logical" reading, from left to right and from top to bottom, and the reading of the xml (order of declaration of the e
s/xml/`<abbr>XML</abbr>`/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- accessibilityTraversalAfter: takes an id in parameter and allows to specify to the view that it must be described by the accessibility after the view passed in parameter.
s/accessibilityTraversalAfter/`accessibilityTraversalAfter`/ (backquotes)

I'd say something's missing, possibly this:
s/by the accessibility/by the Accessibility API/
(same line 212)

s/after the view passed/after the view was passed/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- accessibilityTraversalBefore : takes an id in parameter and allows to specify to the view that it must be described by the accessibility before the view passed in parameter.
```
- `accessibilityTraversalBefore`: takes an `id` in parameter and allows to specify to the view that it must be described by the accessibility before the view is passed in parameter.
```

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +Note: these attributes can be used directly in the xml but also in the code via the methods setAccessibilityTraversalAfter and setAccessibilityTraversalBefore. These methods are available for any ele
```
Note: these attributes can be used directly in the <abbr>XML</abbr> but also in the code via the `setAccessibilityTraversalAfter` and `setAccessibilityTraversalBefore`methods. These methods are available for any element that inherits from View.
```

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- Dialogs opening are vocalized
Missing punctuation (this line and a few below in this list).

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +To not confuse navigation with a screen reader, it is necessary to vocalize only the significant elements. Decorative elements, such as illustrations, should not be vocalized.
s/To not confuse navigation with a screen reader/To avoid confusion for a screen-reader user/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- No invisible elements are vocalized
Missing punctuation.

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- <img src="../../../images/montagnard.png" alt="example of a decorative image" width="256" height="95"> pas de `contentDescription`
s/pas de `contentDescription`/no `contentDescription`/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- <img src="../../../images/edit.png" alt="xample of informative icon - edit" width="48" height="48"> `imageView.setContentDescription("éditer le nom de l’image")`
s/xample/example/
s/éditer le nom de l’image/edit the image’s name/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +It is recommended to group the linked elements for vocalization when this increase efficiency and comprehension.
s/group the linked elements/group similar elements/
(suggestion, I'm not sure of how a native speaker would say that actually)

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- Linked elements are grouped in the same block of announcements for vocalization
Missing punctuation.

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +Within the same screen, content have sometimes different sections, with a header for each of them. It is possible with the Talkback screen reader to navigate by headings, rather than by elements. Thi
s/content have sometimes/content is sometimes split into/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +To recognize headers, an attribute in the XML layout must be added to the elements : **accessibilityHeading**
s/XML/`<abbr>XML</abbr>`/
s/**accessibilityHeading**/**`accessibilityHeading`**/ (add backquotes)

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +## Hide elements from accessibility
s/from accessibility/from  the Accessibility API/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +- `noHideDescendants` (4)&nbsp;: the view is not important for accessibility, but all its daughter views are. It hide all the elements of a view from accessibility at once. Very useful on custom elem
s/daughter/child/
s/It hide/It hides/

2020-12-03 17:45 UTC, notabene commented on src/en/mobile/android/development/vocal-navigation.md
> +Note: the "importantForAccessibility" attribute is available for any element that inherits from `View'.
s/importantForAccessibility/`importantForAccessibility`/ (missing backquotes)

2020-12-04 13:40 UTC, sdeschamps-orange approved these changes

2020-12-04 13:52 UTC, merged